### ISSUE TITLE
Update `proto-props` dependency

### ISSUE THREAD

**Issue by sindresorhus** [dustinspecker/is-proto-prop#78]
https://github.com/sindresorhus/proto-props/releases/tag/v2.0.0

And then update this dependency in `eslint-plugin-no-use-extend-native`.

**Comment by dustinspecker** [comment]
https://github.com/dustinspecker/eslint-plugin-no-use-extend-native/commit/03bf515483ed750bac12ca5b2407e2516896c54f

released 0.4.0 of eslint-plugin-no-use-extend-native with this
